# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'tsla-log' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for tsla-log
pod 'SVProgressHUD'
pod 'Alamofire'
pod 'SwiftyJSON'

end
